/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Radwa
 */
import javax.swing.ImageIcon;
import logic.*;

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    private final String[] levels; //comboBox selections
    public static String selection = "";
    private Score score;
    private User user ;
    SudokuLevels home = new SudokuLevels();

    public HomePage(User user) {
        this.levels = new String[]{"Select a game: ", "easy", "medium", "hard"};
        initComponents();
        setTitle("SUDOKU");
        ImageIcon image = new ImageIcon("C:\\Users\\nadee\\Desktop\\TheBigProject\\src\\com\\SProject\\logo.png");
        this.setIconImage(image.getImage()); //change icon of frame
        
        this.user = user ;
        score= new Score(user); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();
        select = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 102, 129));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logOut.setForeground(new java.awt.Color(134, 90, 136));
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel1.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 190, 50));

        playBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        playBtn.setForeground(new java.awt.Color(134, 90, 136));
        playBtn.setText("Play Now !");
        playBtn.setEnabled(false);
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });
        jPanel1.add(playBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 50));

        scoreButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        scoreButton.setForeground(new java.awt.Color(134, 90, 136));
        scoreButton.setText("Score ");
        scoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreButtonActionPerformed(evt);
            }
        });
        jPanel1.add(scoreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 190, 50));

        select.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel<>(levels));
        select.setToolTipText("Select a Game:");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 200, 50));

        label1.setFont(new java.awt.Font("Showcard Gothic", 1, 30)); // NOI18N
        label1.setText("Welcome to sudoku game..");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 460, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void scoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreButtonActionPerformed
        // TODO add your handling code here:
        score.setVisible(true);
       
    }//GEN-LAST:event_scoreButtonActionPerformed

    

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == select) {
            selection = (String) select.getSelectedItem();
        }
        switch (selection) {
            case "easy":
                home.easy(user);
                //dispose();
                break;
            case "medium":
                home.medium(user);
                //dispose();
                break;
            case "hard":
                home.hard(user);
                //dispose();
                break;

        }
    }//GEN-LAST:event_selectActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        dispose();  // on click close homePage
        LoginPage login = new ui.LoginPage();
        login.setVisible(true);  //view login bage

    }//GEN-LAST:event_logOutActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            User user ;
            @Override
            public void run() {
                new HomePage(user).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton scoreButton;
    private javax.swing.JComboBox<String> select;
    // End of variables declaration//GEN-END:variables
}
